### ISSUE TITLE
Datasets sometimes fail to load only some columns

### ISSUE THREAD

**Issue by clayote** [lllangWV/ParquetDB#4]
I'm trying to keep a simple key-value store in a ParquetDB. For my convenience, I'd like a function that updates a key with a new value if it already exists, and otherwise inserts a key with that value.

So I wrote this code:

```python
from tempfile import mkdtemp

from parquetdb import ParquetDB
import pyarrow.compute as pc

initial = {
		"global": [
			{
				"key": b"\xb4_lise_schema_version",
				"value": b"\x00",
			},
			{"key": b"\xabmain_branch", "value": b"\xa5trunk"},
			{"key": b"\xa6branch", "value": b"\xa5trunk"},
			{"key": b"\xa4turn", "value": b"\x00"},
			{"key": b"\xa4tick", "value": b"\x00"},
			{"key": b"\xa8language", "value": b"\xa3eng"},
		]
	}

dir = mkdtemp()
db = ParquetDB(dir)

def set_global(key: bytes, value: bytes):
	try:
		id_ = db.read("global", filters=[pc.field("key") == key], columns=["id"])["id"][0].as_py()
		db.update(
			{"id": id_, "key": key, "value": value}, "global"
		)
	except IndexError:
		db.create({"key": key, "value": value}, "global")


set_global(b"\xa6branch", b"\xa5tronc")
set_global(b"\xa4turn", b"\x00")
```

The first call to `set_global` goes fine, but the second one gives me:

```pyarrow.lib.ArrowInvalid: No match for FieldRef.Name(key) in```

Which field goes missing seems unpredictable.

**Comment by lllangWV** [comment]
Hey, 

I took a look at the issue. The problem stems from the `except IndexError:` block. This block is intended to catch an `IndexError`, but since the code doesn't explicitly raise this error, it results in the database not being updated as expected. I’ll need to implement custom error handling to provide clearer feedback. I'll work on adding that soon.

In the meantime, here's a working version of your code:

```python
from tempfile import mkdtemp
import logging

from parquetdb import ParquetDB
import pyarrow.compute as pc

# Set up logging for debugging
logger = logging.getLogger('parquetdb')
logger.setLevel(logging.DEBUG)
ch = logging.StreamHandler()
ch.setLevel(logging.DEBUG)
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
ch.setFormatter(formatter)
logger.addHandler(ch)

# Initial global data
initial = {
    "global": [
        {"key": b"\xb4_lise_schema_version", "value": b"\x00"},
        {"key": b"\xabmain_branch", "value": b"\xa5trunk"},
        {"key": b"\xa6branch", "value": b"\xa5trunk"},
        {"key": b"\xa4turn", "value": b"\x00"},
        {"key": b"\xa4tick", "value": b"\x00"},
        {"key": b"\xa8language", "value": b"\xa3eng"},
    ]
}

# Create a temporary directory for the Parquet database
dir = mkdtemp()
db = ParquetDB(dir)

# Function to set or update global key-value pairs
def set_global(key: bytes, value: bytes):
    try:
        id_ = db.read(dataset_name="global", filters=[pc.field("key") == key], columns=["id"])["id"][0].as_py()
        db.update({"id": id_, "key": key, "value": value}, "global")
    except IndexError:
        db.create({"key": key, "value": value}, "global")

# Example usage of the function
set_global(b"\xa6branch", b"\xa5tronc")
set_global(b"\xa4turn", b"\x00")

df = db.read(dataset_name="global").to_pandas()
print(df)
print('-'*200)

set_global(b"\xa6branch", b"\x00")
df = db.read(dataset_name="global").to_pandas()
print(df)
```

The output is:

```bash
             key         value  id
0  b'\xa6branch'  b'\xa5tronc'   0
1    b'\xa4turn'       b'\x00'   1

------------------------------------------------------------------------------------------------

             key    value  id
0  b'\xa6branch'  b'\x00'   0
1    b'\xa4turn'  b'\x00'   1
```

Let me know if you need further clarification or adjustments.

Best,

Logan Lang

**Comment by clayote** [comment]
When I run your code with ParquetDB 0.0.6, I get

```
/home/sanotehu/.local/share/virtualenv/LiSE/bin/python /home/sanotehu/.config/JetBrains/PyCharm2024.2/scratches/scratch_11.py 
2024-10-07 15:13:31,320 - parquetdb.parquetdb - INFO - datasets_dir: /tmp/tmp6yf45rhs
2024-10-07 15:13:31,320 - parquetdb.parquetdb - INFO - dataset_names: []
2024-10-07 15:13:31,320 - parquetdb.parquetdb - INFO - reserved_table_names: ['tmp']
2024-10-07 15:13:31,320 - parquetdb.parquetdb - INFO - n_cores: 8
2024-10-07 15:13:31,320 - parquetdb.parquetdb - INFO - output_formats: ['batch_generator', 'table', 'dataset']
2024-10-07 15:13:31,322 - parquetdb.parquet_datasetdb - INFO - dir: /tmp/tmp6yf45rhs
2024-10-07 15:13:31,322 - parquetdb.parquet_datasetdb - INFO - reserved_dataset_names: ['tmp']
2024-10-07 15:13:31,322 - parquetdb.parquet_datasetdb - INFO - n_cores: 8
2024-10-07 15:13:31,322 - parquetdb.parquet_datasetdb - INFO - output_formats: ['batch_generator', 'table', 'dataset']
2024-10-07 15:13:31,322 - parquetdb.parquet_datasetdb - INFO - Loading data from /tmp/tmp6yf45rhs/global
2024-10-07 15:13:31,322 - parquetdb.parquet_datasetdb - INFO - Loading only columns: ['id']
2024-10-07 15:13:31,322 - parquetdb.parquet_datasetdb - INFO - Using filter: (key == "A66272616E6368")
2024-10-07 15:13:31,324 - parquetdb.parquet_datasetdb - INFO - Loading data in one table
Traceback (most recent call last):
  File "/home/sanotehu/.config/JetBrains/PyCharm2024.2/scratches/scratch_11.py", line 41, in <module>
    set_global(b"\xa6branch", b"\xa5tronc")
  File "/home/sanotehu/.config/JetBrains/PyCharm2024.2/scratches/scratch_11.py", line 35, in set_global
    id_ = db.read(dataset_name="global", filters=[pc.field("key") == key], columns=["id"])["id"][0].as_py()
  File "/home/sanotehu/.local/share/virtualenv/LiSE/lib/python3.10/site-packages/parquetdb/utils.py", line 24, in wrapper
    result = func(*args, **kwargs)
  File "/home/sanotehu/.local/share/virtualenv/LiSE/lib/python3.10/site-packages/parquetdb/parquetdb.py", line 113, in read
    return dataset_db.read(**all_args)
  File "/home/sanotehu/.local/share/virtualenv/LiSE/lib/python3.10/site-packages/parquetdb/utils.py", line 24, in wrapper
    result = func(*args, **kwargs)
  File "/home/sanotehu/.local/share/virtualenv/LiSE/lib/python3.10/site-packages/parquetdb/parquet_datasetdb.py", line 201, in read
    data = self._load_data(columns=columns, filter=filter_expression, 
  File "/home/sanotehu/.local/share/virtualenv/LiSE/lib/python3.10/site-packages/parquetdb/parquet_datasetdb.py", line 639, in _load_data
    return dataset.to_table(columns=columns,filter=filter)
  File "pyarrow/_dataset.pyx", line 553, in pyarrow._dataset.Dataset.to_table
  File "pyarrow/_dataset.pyx", line 399, in pyarrow._dataset.Dataset.scanner
  File "pyarrow/_dataset.pyx", line 3557, in pyarrow._dataset.Scanner.from_dataset
  File "pyarrow/_dataset.pyx", line 3475, in pyarrow._dataset.Scanner._make_scan_options
  File "pyarrow/_dataset.pyx", line 3409, in pyarrow._dataset._populate_builder
  File "pyarrow/_compute.pyx", line 2724, in pyarrow._compute._bind
  File "pyarrow/error.pxi", line 155, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: No match for FieldRef.Name(key) in 

Process finished with exit code 1
```

But I see there's a new release. Here's the output with that one...

```
/home/sanotehu/.local/share/virtualenv/LiSE/bin/python /home/sanotehu/.config/JetBrains/PyCharm2024.2/scratches/scratch_11.py 
2024-10-07 15:14:28,518 - parquetdb.core.parquetdb - INFO - datasets_dir: /tmp/tmpedh082hg
2024-10-07 15:14:28,518 - parquetdb.core.parquetdb - INFO - dataset_names: []
2024-10-07 15:14:28,518 - parquetdb.core.parquetdb - INFO - reserved_table_names: ['tmp']
2024-10-07 15:14:28,518 - parquetdb.core.parquetdb - INFO - n_cores: 8
2024-10-07 15:14:28,518 - parquetdb.core.parquetdb - INFO - output_formats: ['batch_generator', 'table', 'dataset']
2024-10-07 15:14:28,518 - parquetdb.core.parquet_datasetdb - INFO - dir: /tmp/tmpedh082hg
2024-10-07 15:14:28,518 - parquetdb.core.parquet_datasetdb - INFO - reserved_dataset_names: ['tmp']
2024-10-07 15:14:28,518 - parquetdb.core.parquet_datasetdb - INFO - n_cores: 8
2024-10-07 15:14:28,518 - parquetdb.core.parquet_datasetdb - INFO - output_formats: ['batch_generator', 'table', 'dataset']
2024-10-07 15:14:28,518 - parquetdb.core.parquet_datasetdb - INFO - Loading data from /tmp/tmpedh082hg/global
2024-10-07 15:14:28,518 - parquetdb.core.parquet_datasetdb - INFO - Loading only columns: ['id']
2024-10-07 15:14:28,518 - parquetdb.core.parquet_datasetdb - INFO - Using filter: (key == "A66272616E6368")
2024-10-07 15:14:28,518 - parquetdb.core.parquet_datasetdb - INFO - Loading data in one table
Traceback (most recent call last):
  File "/home/sanotehu/.config/JetBrains/PyCharm2024.2/scratches/scratch_11.py", line 41, in <module>
    set_global(b"\xa6branch", b"\xa5tronc")
  File "/home/sanotehu/.config/JetBrains/PyCharm2024.2/scratches/scratch_11.py", line 35, in set_global
    id_ = db.read(dataset_name="global", filters=[pc.field("key") == key], columns=["id"])["id"][0].as_py()
  File "/home/sanotehu/.local/share/virtualenv/LiSE/lib/python3.10/site-packages/parquetdb/utils/general_utils.py", line 24, in wrapper
    result = func(*args, **kwargs)
  File "/home/sanotehu/.local/share/virtualenv/LiSE/lib/python3.10/site-packages/parquetdb/core/parquetdb.py", line 114, in read
    return dataset_db.read(**all_args)
  File "/home/sanotehu/.local/share/virtualenv/LiSE/lib/python3.10/site-packages/parquetdb/utils/general_utils.py", line 24, in wrapper
    result = func(*args, **kwargs)
  File "/home/sanotehu/.local/share/virtualenv/LiSE/lib/python3.10/site-packages/parquetdb/core/parquet_datasetdb.py", line 202, in read
    data = self._load_data(columns=columns, filter=filter_expression, 
  File "/home/sanotehu/.local/share/virtualenv/LiSE/lib/python3.10/site-packages/parquetdb/core/parquet_datasetdb.py", line 640, in _load_data
    return dataset.to_table(columns=columns,filter=filter)
  File "pyarrow/_dataset.pyx", line 553, in pyarrow._dataset.Dataset.to_table
  File "pyarrow/_dataset.pyx", line 399, in pyarrow._dataset.Dataset.scanner
  File "pyarrow/_dataset.pyx", line 3557, in pyarrow._dataset.Scanner.from_dataset
  File "pyarrow/_dataset.pyx", line 3475, in pyarrow._dataset.Scanner._make_scan_options
  File "pyarrow/_dataset.pyx", line 3409, in pyarrow._dataset._populate_builder
  File "pyarrow/_compute.pyx", line 2724, in pyarrow._compute._bind
  File "pyarrow/error.pxi", line 155, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: No match for FieldRef.Name(key) in 
```

Pretty much the same for me. Is it possible we're looking at operating-system-specific behavior? Here's my `uname -a`:
```
Linux sanotehu-Lenovo-YOGA-730-15IWL 5.15.0-122-generic #132-Ubuntu SMP Thu Aug 29 13:45:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by lllangWV** [comment]
Hey,

I looked into this.

I'm running the code on both Windows and RHEL Linux, and in both environments, it's executing correctly and producing the expected output.

I've also tested it across Python versions 3.8, 3.9, 3.10, and 3.11, and everything seems to be working fine on my end.

It's strange that you're encountering issues. I'm not sure why it's not working on your system.

Could you walk me through how you installed `parquetdb`? I noticed you're using a virtual environment—could you explain the steps you took to set that up?

**Comment by lllangWV** [comment]
Wait, I just realized the code I sent you earlier was wrong. I forgot to take out the IndexError for the try except block. This is the code

```python
dir = mkdtemp()
db = ParquetDB(dir)

def set_global(key: bytes, value: bytes):
	try:
		id_ = db.read(dataset_name="global", filters=[pc.field("key") == key], columns=["id"])["id"][0].as_py()
		db.update(
			{"id": id_, "key": key, "value": value}, "global"
		)
	except:
		db.create({"key": key, "value": value}, "global")


set_global(b"\xa6branch", b"\xa5tronc")
set_global(b"\xa4turn", b"\x00")

df = db.read(dataset_name="global").to_pandas()
print(df)
set_global(b"\xa6branch", b"\x00")
print('-'*200)

df = db.read(dataset_name="global").to_pandas()
print(df)
```

My bad!

**Comment by clayote** [comment]
Thanks, I think I get it now. In that case, my first feature request: ParquetDB either should or should not return an empty table when there's no match, I care not; but it should do one or the other *all the time*.
